server:
  port: ${PORT:5556}

spring:
  application:
    name: mobile-api
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  cache:
    caffeine:
      spec: maximumSize=200,expireAfterAccess=600s
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_HOST:localhost}:2181
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411/

management.security.enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true



