server:
  port: ${PORT:4444}

spring:
  application:
    name: time-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      dk.trustworks.network.clients.WorkClient: DEBUG
      org.springframework.cloud.client.hypermedia: DEBUG
      org.springframework: WARN
      org.hibernate: WARN
  jpa:
    hibernate.ddl-auto: none
  datasource:
      url: ${URL:jdbc:mysql://localhost:3306/timemanager?noDatetimeStringSync=true&characterEncoding=utf8}
      username: ${USERNAME:root}
      password: ${PASSWORD:}
      hikari:
        maximum-pool-size: 2
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_HOST:localhost}:2181
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411/

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

feign:
  compression:
    response:
      enabled: true

# Logging



management.security.enabled: false