server:
  port: ${PORT:2223}

spring:
  application:
    name: invoice-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/invoicemanager?noDatetimeStringSync=true&characterEncoding=utf8
    username: root
    password:
    hikari:
      maximum-pool-size: 2


eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true


flyway:
  baseline-version: 1 # version to start migration
  enabled: true # Enable flyway.
  locations: classpath:db/migration # locations of migrations scripts
  schemas: invoicemanager
  baseline-on-migrate: true # schemas to update

management.security.enabled: false

spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest