server:
  port: ${PORT:5555}

spring:
  application:
    name: web-api
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  cache:
    caffeine:
      spec: maximumSize=200,expireAfterAccess=10s,recordStats,
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_HOST:localhost}:2181
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411/

management.security.enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

invoice-service:
  ribbon:
    ServerListRefreshInterval: 2000
    retryableStatusCodes: 404, 500, 502
    MaxAutoRetries: 5
    ConnectTimeout: 5000
    ReadTimeout: 5000

client-service:
  ribbon:
    ServerListRefreshInterval: 2000
    retryableStatusCodes: 404, 500, 502
    MaxAutoRetries: 5
    ConnectTimeout: 5000
    ReadTimeout: 5000

time-service:
  ribbon:
    ServerListRefreshInterval: 2000
    retryableStatusCodes: 404, 500, 502
    MaxAutoRetries: 5
    ConnectTimeout: 5000
    ReadTimeout: 5000

ribbon:
  eureka:
    enabled: true


# Increase the Hystrix timeout to 60s (globally)
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

feign:
  client:
    config:
      time-service:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: full
        requestInterceptors: dk.trustworks.network.FooRequestInterceptor
  compression:
    response:
      enabled: true

spring.rabbitmq.host: ${RABBITMQ_HOST:127.0.0.1}
spring.rabbitmq.port: ${RABBITMQ_PORT:5672}
spring.rabbitmq.username: ${RABBIT_USERNAME:guest}
spring.rabbitmq.password: ${RABBIT_PASSWORD:guest}